// Common program/course options for the dropdown.
// "Other" lets the user type a custom program not in this list.
export const PROGRAM_OPTIONS = [
  'BS Computer Science',
  'BS Information Technology',
  'BS Information Systems',
  'BS Civil Engineering',
  'BS Electrical Engineering',
  'BS Electronics Engineering',
  'BS Mechanical Engineering',
  'BS Industrial Engineering',
  'BS Architecture',
  'BS Accountancy',
  'BS Accounting Information System',
  'BS Business Administration',
  'BS Entrepreneurship',
  'BS Economics',
  'BS Office Administration',
  'BS Nursing',
  'BS Pharmacy',
  'BS Physical Therapy',
  'BS Medical Technology',
  'BS Psychology',
  'BS Social Work',
  'BS Criminology',
  'BS Hospitality Management',
  'BS Tourism Management',
  'BS Biology',
  'BS Mathematics',
  'BS Chemistry',
  'BS Agriculture',
  'BS Forestry',
  'BS Fisheries',
  'AB Communication',
  'AB Political Science',
  'AB English',
  'Bachelor of Elementary Education',
  'Bachelor of Secondary Education',
  'Other',
];